: "${DV_MINIO_STORAGE_NAME:=nese-minio}"
: "${DV_MINIO_ENDPOINT_REGION:=us-east-1}"
: "${DV_MINIO_ENDPOINT_PROXY_URL:=}"
: "${DV_MINIO_ENDPOINT_URL:=dp.lmtgtm.org}"
: "${DV_MINIO_ACCESS_KEY:=key}"
: "${DV_MINIO_SECRET_KEY:=value}"

echo "add storage:"
echo "name: ${DV_MINIO_STORAGE_NAME}"
echo "region: ${DV_MINIO_ENDPOINT_REGION}"
echo "proxy_url: ${DV_MINIO_ENDPOINT_PROXY_URL}"
echo "url: ${DV_MINIO_ENDPOINT_URL}"

# exit 1
PAYARA=/usr/local/payara6/bin/
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.type=s3"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.label=${DV_MINIO_STORAGE_NAME}"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.bucket-name=${DV_MINIO_STORAGE_NAME}"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.upload-redirect=true"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.profile=default"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.download-redirect=true"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.ingestsizelimit=0"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.url-expiration-minutes=120"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.path-style-access=true"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.custom-endpoint-region=${DV_MINIO_ENDPOINT_REGION}"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.proxy-url=${DV_MINIO_ENDPOINT_PROXY_URL}"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.custom-endpoint-url=${DV_MINIO_ENDPOINT_URL}"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.access-key=${DV_MINIO_ACCESS_KEY}"
${PAYARA}/asadmin $ASADMIN_OPTS create-jvm-options "-Ddataverse.files.nese_minio.secret-key=${DV_MINIO_SECRET_KEY}"
